language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("LaTeX"));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(Coveralls.process_folder())'